# Éléments finis - TPs 2 à 11

* Quelques librairies Python toujours utiles

In [1]:
import numpy as np

* Création du maillage de la table 1 du cours avec un champ de déplacement arbitraire

In [2]:
nodes = np.array([[0, 0],
                  [1, 0],
                  [1, 1],
                  [0, 1]])

elements = np.array([[0, 1, 3],
                     [1, 2, 3]])

displacements = np.array([[0, 0],
                          [0.5, 0],
                          [1, 1],
                          [0.5, 1]])

* Création d'un point $\mathbf{M}$ en coordonnées de référence pour les tests (par défaut le centre du triangle de référence)

In [3]:
Mref = np.array([1/3,1/3])

* Création d'une fonction pour évaluer toutes les fonctions de forme du triangle de référence P1 en un point et test de la fonction (section 4.3.1 du cours)

In [5]:
def Nref_triangle_P1(xref):
    Nref = np.array([1-xref[0]-xref[1],
                     xref[0],
                     xref[1]])
    return Nref

print(Nref_triangle_P1(np.array([0,0])))
print(Nref_triangle_P1(np.array([1,0])))
print(Nref_triangle_P1(np.array([0,1])))
print(Nref_triangle_P1(Mref))

# sortie de output_2.txt pour FE-JAM TP 2
np.savetxt("output_2.txt", Nref_triangle_P1(Mref).reshape(-1), '%.8e', delimiter='\n', newline='\n')

[1 0 0]
[0 1 0]
[0 0 1]
[0.33333333 0.33333333 0.33333333]


* Création d'une fonction interpolant le champ de déplacement au point $\mathbf{M}$ pour un triangle donné et test de la fonction (équation (5) et exemple 5 du cours)

In [6]:
def interpolate_displacement(nodes, K, displacements, Nref):
    nb_nodes_loc = K.shape[0]
    #for u0_M,K.shape[0]=3
    dimension = nodes.shape[1]
    #for displacements,nodes.shape[1]=2
    u = np.zeros(dimension)
    #u est un vecteur
    for i in range(0,dimension):
        for nloc in range(0,nb_nodes_loc):
            n = K[nloc]
            u[i] = u[i] + Nref[nloc]*displacements[n][i]
    return u

u0_M = interpolate_displacement(nodes, elements[0,:], displacements, Nref_triangle_P1(Mref))
print(u0_M)
u1_M = interpolate_displacement(nodes, elements[1,:], displacements, Nref_triangle_P1(Mref))
print(u1_M)

# sortie de output_3.txt pour FE-JAM TP 3
np.savetxt("output_3.txt", np.array([u0_M,u1_M]).reshape(-1), '%.8e', delimiter='\n', newline='\n')

[0.33333333 0.33333333]
[0.66666667 0.66666667]


* Création d'une fonction pour évaluer les gradients de toutes les fonctions de forme du triangle de référence P1 en un point et test de la fonction (section 4.3.1 du cours)

In [ ]:
def gradNref_triangle_P1(xref):
    gradNref = np.array([[???, ???],
                         [???, ???],
                         [???, ???]])
    return gradNref

print(gradNref_triangle_P1(Mref))

# sortie de output_4.txt pour FE-JAM TP 4
np.savetxt("output_4.txt", gradNref_triangle_P1(Mref).reshape(-1), '%.8e', delimiter='\n', newline='\n')

* Création d'une fonction pour calculer le gradient de la transformation $\mathbf{F}$ et test de la fonction (équation (7) du cours)

In [ ]:
def compute_gradF(nodes, K, gradNref):
    nb_nodes_loc = K.shape[0]
    dimension = nodes.shape[1]
    gradF = np.zeros(???)
    for i in range(0,???):
        for j in range(0,???):
            for nloc in range(0,???):
                n = K[nloc]
                gradF[i,j] = gradF[i,j] + ???
    return gradF

gradF0_M = compute_gradF(nodes, elements[0,:], gradNref_triangle_P1(Mref))
print(gradF0_M)
gradF1_M = compute_gradF(nodes, elements[1,:], gradNref_triangle_P1(Mref))
print(gradF1_M)

# sortie de output_5.txt pour FE-JAM TP 5
np.savetxt("output_5.txt", np.array([gradF0_M,gradF1_M]).reshape(-1), '%.8e', delimiter='\n', newline='\n')

* Création d'une fonction pour calculer les gradients de toutes les fonctions de forme d'un triangle P1 et test de la fonction (équation (8) du cours)

In [ ]:
def compute_gradN(K, gradF, gradNref):
    gradN = ???
    return gradN

gradN0_M = compute_gradN(elements[0,:], gradF0_M, gradNref_triangle_P1(Mref))
print(gradN0_M)
gradN1_M = compute_gradN(elements[1,:], gradF1_M, gradNref_triangle_P1(Mref))
print(gradN1_M)

# sortie de output_6.txt pour FE-JAM TP 6
np.savetxt("output_6.txt", np.array([gradN0_M,gradN1_M]).reshape(-1), '%.8e', delimiter='\n', newline='\n')

* Création d'une fonction interpolant le gradient du champ de déplacement au point $\mathbf{M}$ pour un triangle donné et test de la fonction (équation (9) et exemple 6 du cours)

In [ ]:
def interpolate_grad_displacement(nodes, K, displacements, gradN):
    nb_nodes_loc = K.shape[0]
    dimension = nodes.shape[1]
    gradu = np.zeros(???)
    for i in range(0,???):
        for j in range(0,???):
            for nloc in range(0,???):
                n = K[nloc]
                gradu[i,j] = gradu[i,j] + ???
    return gradu

gradu0_M = interpolate_grad_displacement(nodes, elements[0,:], displacements, gradN0_M)
print(gradu0_M)
gradu1_M = interpolate_grad_displacement(nodes, elements[1,:], displacements, gradN1_M)
print(gradu1_M)

# sortie de output_7.txt pour FE-JAM TP 7
np.savetxt("output_7.txt", np.array([gradu0_M,gradu1_M]).reshape(-1), '%.8e', delimiter='\n', newline='\n')

* Réglage du champ de déplacement et des degrés de liberté (section 4.3 du cours)

In [ ]:
displacements = np.array([[0, 0],
                          [0, 0],
                          [0, 0.01],
                          [0, 0.01]])
dofs = np.array([[0, 0],
                 [1, 0],
                 [1, 0],
                 [0, 0]])

* Récupération du tenseur d'ordre 4 $\tilde{\mathbb{C}}$ des TPs précédents

In [ ]:
def produit_tensoriel(u,v):
    res = np.zeros((u.shape[0],v.shape[0]))
    for i in range(0,u.shape[0]):
        for j in range(0,v.shape[0]):
            res[i,j] = u[i]*v[j]
    return res
I2 = np.eye(2)
I4s = np.zeros((2,2,2,2))
for i in range(0,2):
    for j in range(0,2):
       for k in range(0,2):
            for l in range(0,2):
                I4s[i,j,k,l] = 0.5*((i == k) * (j == l) + (i == l) * (j == k))
_mu = 4
_lambda = 2
C_elastic_s = 2*_mu*I4s + _lambda*produit_tensoriel(I2.reshape(2*2),I2.reshape(2*2)).reshape(2,2,2,2)
print(C_elastic_s.reshape(2*2,2*2))

* Calcul des matrices et vecteurs de contributions locales (sections 3.2.2 et 4.3.4 du cours) puis assemblage dans la matrice et le vecteur globaux (sections 3.2.3 et 4.3.5 du cours)

In [ ]:
dimension = nodes.shape[1]
nb_nodes = nodes.shape[0]
nb_elements = elements.shape[0]
nb_nodes_per_element = elements.shape[1]

matKlocs = np.zeros((nb_elements,nb_nodes_per_element,dimension,nb_nodes_per_element,dimension))
vecBlocs = np.zeros((nb_elements,nb_nodes_per_element,dimension))

matK = np.zeros(???)
vecB = np.zeros(???)

for id_element in range(0,nb_elements):
    K = elements[id_element,:]
    print("Contributions de l'élément "+str(K)+" :")
    
    # calcul des matrices et vecteurs de contributions locales
    # on se restreint à un point de quadrature de coordonnées xref et de poids wref
    xref = np.array([1/3,1/3])
    wref = 0.5
    gradNref_q = gradNref_triangle_P1(xref)
    gradF_q = compute_gradF(nodes,K, gradNref_q)
    gradN_q = compute_gradN(K, gradF_q, gradNref_q)
    detF_q = np.linalg.det(gradF_q)
    
    matKloc = np.zeros(???)
    vecBloc = np.zeros(???)
    for mloc in range(0,???):
        for i in range(0,???):
            for nloc in range(0,???):
                for k in range(0,???):
                   for j in range(0,???):
                      for l in range(0,???):
                            matKloc[mloc,i,nloc,k] = matKloc[mloc,i,nloc,k] \
                                + ???
    print(matKloc.reshape(???,???))
    print(vecBloc.reshape(???,1))
    matKlocs[id_element,:,:,:,:] = matKloc
    vecBlocs[id_element,:,:] = vecBloc
    
    # assemblage vers la matrice et le vecteur globaux
    for mloc in range(0,???):
        m = ???
        for i in range(0,???):
            for nloc in range(0,???):
                n = ???
                for k in range(0,???):
                    matK[m,i,n,k] = matK[m,i,n,k] + ???
            vecB[m,i] = vecB[m,i] + ???

print("Matrice et vecteur globaux :")
print(matK.reshape(???,???))
print(vecB.reshape(???,1))

# sortie de output_8.txt pour FE-JAM TP 8
np.savetxt("output_8.txt", matKlocs.reshape(-1), '%.8e', delimiter='\n', newline='\n')
# sortie de output_9.txt pour FE-JAM TP 9
np.savetxt("output_9.txt", matK.reshape(-1), '%.8e', delimiter='\n', newline='\n')

* Implémentation des conditions aux limites de Dirichlet (sections 3.2.3 et et 4.3.5 du cours)

In [ ]:
matKtilde = matK.copy()
vecBtilde = vecB.copy()
for m in range(0,???):
    for i in range(0,???):
        if(dofs[m,i] == 0):
            ???

matKtilde = matKtilde.reshape(???,???)
vecBtilde = vecBtilde.reshape(???,1)
print(matKtilde)
print(vecBtilde)

# sortie de output_10.txt pour FE-JAM TP 10
np.savetxt("output_10.txt", np.concatenate((matKtilde,vecBtilde),axis=1).reshape(-1), '%.8e', delimiter='\n', newline='\n')

* Résolution du système linéaire et calcul des forces nodales

In [ ]:
displacements = np.linalg.solve(matKtilde, vecBtilde).reshape(???,???)
print("Déplacements :")
print(displacements)

forces = ???
forces = forces.reshape(???,???)
print("Forces :")
print(forces)

# sortie de output_11.txt pour FE-JAM TP 11
np.savetxt("output_11.txt", forces.reshape(-1), '%.8e', delimiter='\n', newline='\n')